Repository grooteogi/backend, pull requests merged in 2022-05, with the labels that each got.

#74 fix fetch multiple bags hibernate error
  api/src/main/java/grooteogi/domain/Heart.java
  api/src/main/java/grooteogi/domain/Post.java
  api/src/main/java/grooteogi/domain/User.java
Labels: fix

#81 FIX get reservation
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/domain/Reservation.java
  api/src/main/java/grooteogi/dto/ReservationRes.java
  api/src/main/java/grooteogi/repository/PostRepository.java
  api/src/main/java/grooteogi/repository/ReservationRepository.java
  api/src/main/java/grooteogi/service/ReservationService.java
Labels: fix

#82 FIX reservation api AND ADD mapper
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/domain/Reservation.java
  api/src/main/java/grooteogi/domain/User.java
  api/src/main/java/grooteogi/dto/ReservationDto.java
  api/src/main/java/grooteogi/dto/ReservationRes.java
  api/src/main/java/grooteogi/mapper/BasicMapper.java
  api/src/main/java/grooteogi/mapper/ReservationMapper.java
  api/src/main/java/grooteogi/repository/ReservationRepository.java
  api/src/main/java/grooteogi/service/ReservationService.java
Labels: fix

#87 refactor: Remove unnecessary timestamp setter
  api/src/main/java/grooteogi/domain/Hashtag.java
  api/src/main/java/grooteogi/domain/Post.java
  api/src/main/java/grooteogi/domain/PostHashtag.java
  api/src/main/java/grooteogi/domain/Reservation.java
  api/src/main/java/grooteogi/domain/Review.java
  api/src/main/java/grooteogi/domain/User.java
  api/src/main/java/grooteogi/domain/UserHashtag.java
  api/src/main/java/grooteogi/domain/UserInfo.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/main/java/grooteogi/service/UserHashtagService.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: fix

#88 refactor: Change date and time type in schedule
  api/src/docs/asciidoc/api.adoc
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/domain/Hashtag.java
  api/src/main/java/grooteogi/domain/Heart.java
  api/src/main/java/grooteogi/domain/Post.java
  api/src/main/java/grooteogi/domain/PostHashtag.java
  api/src/main/java/grooteogi/domain/Reservation.java
  api/src/main/java/grooteogi/domain/Review.java
  api/src/main/java/grooteogi/domain/Schedule.java
  api/src/main/java/grooteogi/domain/User.java
  api/src/main/java/grooteogi/domain/UserHashtag.java
  api/src/main/java/grooteogi/domain/UserInfo.java
  api/src/main/java/grooteogi/dto/PostDto.java
  api/src/main/java/grooteogi/dto/ReservationDto.java
  api/src/main/java/grooteogi/dto/ScheduleDto.java
  api/src/main/java/grooteogi/mapper/DateMapper.java
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/mapper/ReservationMapper.java
  api/src/main/java/grooteogi/mapper/ScheduleMapper.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/test/java/grooteogi/ApiDocumentUtils.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: fix

#93 Add .travis.yml
  api/.travis.yml
Labels: enhancement

#97 Grtg 259 refactor dto related hashtag
  api/src/main/java/grooteogi/controller/HashtagController.java
  api/src/main/java/grooteogi/domain/Hashtag.java
  api/src/main/java/grooteogi/dto/hashtag/HashtagDto.java
  api/src/main/java/grooteogi/mapper/HashtagMapper.java
  api/src/main/java/grooteogi/repository/HashtagRepository.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/test/java/grooteogi/ApiDocumentUtils.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: fix

#94 feat: Divide environment db
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
Labels: enhancement

#92 Refactor dto related reservation
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/domain/Reservation.java
  api/src/main/java/grooteogi/dto/PostDto.java
  api/src/main/java/grooteogi/dto/ReservationDto.java
  api/src/main/java/grooteogi/enums/ReservationType.java
  api/src/main/java/grooteogi/mapper/DateMapper.java
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/mapper/ReservationMapper.java
  api/src/main/java/grooteogi/mapper/ScheduleMapper.java
  api/src/main/java/grooteogi/repository/ReservationRepository.java
  api/src/main/java/grooteogi/repository/ScheduleRepository.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: fix

#96 feat: Add send sms api
  api/build.gradle
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/dto/ReservationDto.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/main/java/grooteogi/utils/SmsClient.java
  api/src/main/resources/application.yml
Labels: enhancement

#99 feat: Create review API
  api/src/main/java/grooteogi/controller/ReviewController.java
  api/src/main/java/grooteogi/domain/Review.java
  api/src/main/java/grooteogi/dto/ReviewDto.java
  api/src/main/java/grooteogi/mapper/ReviewMapper.java
  api/src/main/java/grooteogi/repository/ReviewRepository.java
  api/src/main/java/grooteogi/service/ReviewService.java
Labels: enhancement

#101 Grtg 265 get reservation with filter
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/mapper/ReservationMapper.java
  api/src/main/java/grooteogi/repository/ReservationRepository.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/service/ReservationService.java
Labels: enhancement

#102 Grtg 226 test post api
  api/src/docs/asciidoc/api.adoc
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/dto/LikeDto.java
  api/src/main/java/grooteogi/dto/PostDto.java
  api/src/main/java/grooteogi/dto/ScheduleDto.java
  api/src/main/java/grooteogi/dto/UserDto.java
  api/src/main/java/grooteogi/mapper/HashtagMapper.java
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/mapper/ReservationMapper.java
  api/src/main/java/grooteogi/repository/ReservationRepository.java
  api/src/main/java/grooteogi/repository/ReviewRepository.java
  api/src/main/java/grooteogi/repository/ScheduleRepository.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/resources/static/docs/api.html
  api/src/test/java/grooteogi/PostDocumentationTests.java
Labels: enhancement

#104 Create Heart API
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/controller/ReviewController.java
  api/src/main/java/grooteogi/domain/Reservation.java
  api/src/main/java/grooteogi/repository/HeartRepository.java
  api/src/main/java/grooteogi/service/PostService.java
Labels: enhancement

#105 chore: Add deploy s3 configs to .travis.yml
  .travis.yml
Labels: enhancement

#108 fix: Allow s3 deploy on all branches
  .travis.yml
Labels: enhancement

#107 포스트 수정 혹은 삭제 시, 유저 권한 확인
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/resources/static/docs/api.html
  api/src/test/java/grooteogi/PostDocumentationTests.java
Labels: enhancement

#109 fix: Collect s3 bucket name
  .travis.yml
Labels: fix

#106 refactor: Send sms api
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/dto/ReservationDto.java
  api/src/main/java/grooteogi/service/ReservationService.java
Labels: enhancement

#110 refactor exception enum
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/main/java/grooteogi/service/ReviewService.java
Labels: enhancement

#117 chore: Update application-dev.yml to add redis url
  api/src/main/resources/application-dev.yml
Labels: enhancement

#119 Grtg 283 resolve deploy error
  api/build.gradle
  scripts/deploy.sh
Labels: fix

#120 chore: Add redis config to resolve redis error
  api/src/main/java/grooteogi/config/RedisConfig.java
Labels: enhancement

#124 chore: Add redis cluster config on deployment
  api/src/main/java/grooteogi/config/RedisConfig.java
Labels: enhancement

#113 리뷰 유저 권한 추가 및 리뷰 생성 로직 변경
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/controller/ReviewController.java
  api/src/main/java/grooteogi/domain/Reservation.java
  api/src/main/java/grooteogi/dto/ReservationDto.java
  api/src/main/java/grooteogi/enums/ReservationStatus.java
  api/src/main/java/grooteogi/enums/ReservationType.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/mapper/ReservationMapper.java
  api/src/main/java/grooteogi/mapper/ReviewMapper.java
  api/src/main/java/grooteogi/repository/ReservationRepository.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/main/java/grooteogi/service/ReviewService.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: enhancement

#126 Auth 관련 필요없는 API 삭제, oauth 리팩토링
  api/src/main/java/grooteogi/config/WebConfig.java
  api/src/main/java/grooteogi/controller/AuthController.java
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/dto/UserDto.java
  api/src/main/java/grooteogi/dto/auth/OauthDto.java
  api/src/main/java/grooteogi/mapper/UserMapper.java
  api/src/main/java/grooteogi/service/AuthService.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/main/java/grooteogi/utils/OauthClient.java
  api/src/main/resources/static/docs/api.html
  api/src/test/java/grooteogi/AuthDocumentationTests.java
  api/src/test/java/grooteogi/UserDocumentationTests.java
Labels: fix

#127 포스트 생성 로직 수정 및 매퍼 수정
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/resources/static/docs/api.html
Labels: enhancement

#118 feat : filter post search by heart and review
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/enums/PostFilterEnum.java
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/repository/PostRepository.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
Labels: enhancement

#125 포스트 검색 시, region 조건 추가 및 RegionType enum 클래스 생성 및 스케쥴 도메인 수정
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/domain/Schedule.java
  api/src/main/java/grooteogi/dto/PostDto.java
  api/src/main/java/grooteogi/enums/RegionType.java
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/test/java/grooteogi/ApiDocumentUtils.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: enhancement

#130 refactor: Set token expiration time to env
  api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
  api/src/main/java/grooteogi/service/AuthService.java
  api/src/main/java/grooteogi/utils/JwtProvider.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
Labels: enhancement

#128 예약 Response DTO와 프로필 Response DTO 수정 및 프로필 조회, 수정 로직 개선
  api/src/main/java/grooteogi/controller/ReservationController.java
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/dto/ProfileDto.java
  api/src/main/java/grooteogi/dto/ReservationDto.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/mapper/ReservationMapper.java
  api/src/main/java/grooteogi/mapper/UserInfoMapper.java
  api/src/main/java/grooteogi/mapper/UserMapper.java
  api/src/main/java/grooteogi/repository/UserInfoRepository.java
  api/src/main/java/grooteogi/repository/UserRepository.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: enhancement

#132 AWS S3 컨트롤러 api 테스트
  api/src/test/java/grooteogi/AwsS3DocumentationTests.java
Labels: enhancement

#133 예약 컨트롤러 api 테스트 코드
  api/src/test/java/grooteogi/ReviewDocumentationTests.java
Labels: enhancement

#134 해시태그 컨트롤러 api 테스트
  api/src/test/java/grooteogi/HashtagDocumentationTests.java
Labels: enhancement

#136 AWS 컨트롤러 응답 메세지 추가
  api/src/main/java/grooteogi/controller/AwsS3Controller.java
Labels: enhancement

#137 해시태그 컨트롤러 응답 메세지 추가
  api/src/main/java/grooteogi/controller/HashtagController.java
Labels: enhancement

#138 유저 컨트롤러 api 응답 메세지 추가
  api/src/main/java/grooteogi/controller/UserController.java
Labels: enhancement

#139 Release/0.5.0
  README.md
  api/build.gradle
  docker-compose.local.yml
  docker-compose.yml
Labels: enhancement

#140 포스트 컨트롤러 api 테스트
  api/src/test/java/grooteogi/PostDocumentationTests.java
Labels: enhancement

#141 예약 컨트롤러 api 테스트
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: enhancement

#143 Grtg 309 separate interceptor configs based on profile
  api/src/main/java/grooteogi/config/RedisConfig.java
  api/src/main/java/grooteogi/config/WebConfig.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application.yml
  api/src/main/resources/static/docs/api.html
Labels: enhancement

#145 리뷰 컨트롤러 테스트 코드 문서화
  api/src/docs/asciidoc/api.adoc
  api/src/test/java/grooteogi/ReviewDocumentationTests.java
Labels: documentation

#149 Refresh token 로직 완성
  api/src/main/java/grooteogi/config/UserInterceptor.java
  api/src/main/java/grooteogi/response/RefreshResponse.java
  api/src/main/java/grooteogi/utils/JwtProvider.java
  appspec.yml
Labels: enhancement

#152 hotfix: Add anotation in Schedule domain
  api/src/main/java/grooteogi/domain/Schedule.java
Labels: fix

#146 해시태그 컨트롤러 테스트 코드 문서화
  api/src/docs/asciidoc/api.adoc
  api/src/main/java/grooteogi/dto/HashtagDto.java
  api/src/main/java/grooteogi/mapper/HashtagMapper.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/test/java/grooteogi/HashtagDocumentationTests.java
Labels: documentation

#156 포스트 컨트롤러 테스트 문서화
  api/src/docs/asciidoc/api.adoc
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
Labels: documentation

#157 일반 회원가입 시 로직 변경
  api/src/main/java/grooteogi/domain/UserInfo.java
  api/src/main/java/grooteogi/mapper/UserMapper.java
  api/src/main/java/grooteogi/service/AuthService.java
Labels: enhancement

#151 유저 컨트롤러 테스트코드 문서화
  api/src/docs/asciidoc/api.adoc
  api/src/test/java/grooteogi/UserDocumentationTests.java
Labels: documentation

#160 Auth DTO 이메일 어노테이션 수정 및 회원 탈퇴 request param 삭제
  api/src/main/java/grooteogi/controller/AuthController.java
  api/src/main/java/grooteogi/dto/AuthDto.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/service/AuthService.java
Labels: fix

#159 해시태그 검색 로직 수정
  api/src/main/java/grooteogi/mapper/HashtagMapper.java
  api/src/main/java/grooteogi/service/HashtagService.java
Labels: fix

#161 User API 변경
  api/src/main/java/grooteogi/mapper/UserInfoMapper.java
Labels: fix

#163 Hotfix/add interceptor config for local profile
  api/build.gradle
  api/src/main/java/grooteogi/config/WebConfig.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
  api/src/main/resources/application.yml
Labels: enhancement

#162 Post, Reservation API 변경
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/domain/Reservation.java
  api/src/main/java/grooteogi/enums/ReservationStatus.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/repository/HeartRepository.java
  api/src/main/java/grooteogi/repository/ReservationRepository.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: fix

#164 Hotfix/resolve deployment fail
  api/build.gradle
  api/src/main/java/grooteogi/config/RedisConfig.java
Labels: fix

#165 테스트 서버에서 모든 호스트 접속 허용하도록 변경
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
Labels: fix

#167 로그인 로직 변경
  api/src/main/java/grooteogi/controller/AuthController.java
  api/src/main/java/grooteogi/service/UserService.java
Labels: fix

#168 세미콜론 오류 해결
  api/src/main/java/grooteogi/service/UserService.java
Labels: fix

#166 auth controller 문서화
  api/src/docs/asciidoc/api.adoc
  api/src/main/java/grooteogi/service/AuthService.java
  api/src/test/java/grooteogi/AuthDocumentationTests.java
Labels: documentation, test

#169 특정 url에서 요청한 요청만 처리하도록 수정
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
Labels: fix

#170 테스트 코드 문서화 최종 확인 및 오류 해결
  api/src/test/java/grooteogi/AuthDocumentationTests.java
  api/src/test/java/grooteogi/AwsS3DocumentationTests.java
  api/src/test/java/grooteogi/HashtagDocumentationTests.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
  api/src/test/java/grooteogi/ReviewDocumentationTests.java
  api/src/test/java/grooteogi/UserDocumentationTests.java
Labels: documentation, test

#171 개발 서버에서 모든 호스트 요청 허용하도록 수정
  api/build.gradle
  api/src/main/java/grooteogi/config/WebConfig.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
Labels: enhancement

#172 fix: Update web security config to allow all hosts
  api/src/main/java/grooteogi/config/WebSecurityConfig.java
Labels: fix

#173 마이페이지 필요 API 제작 ( 추가 수정사항 필요 )
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/controller/ReviewController.java
  api/src/main/java/grooteogi/dto/ReservationDto.java
  api/src/main/java/grooteogi/dto/ReviewDto.java
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/mapper/ReservationMapper.java
  api/src/main/java/grooteogi/mapper/ReviewMapper.java
  api/src/main/java/grooteogi/repository/HeartRepository.java
  api/src/main/java/grooteogi/repository/ReviewRepository.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/service/ReservationService.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
  api/src/test/java/grooteogi/ReservationDocumentationTests.java
Labels: enhancement, fix

#175 포스트 상세 조회 시 세션 검사 해제
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
  api/src/test/java/grooteogi/AwsS3DocumentationTests.java
  api/src/test/java/grooteogi/HashtagDocumentationTests.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
  api/src/test/java/grooteogi/ReviewDocumentationTests.java
  api/src/test/java/grooteogi/UserDocumentationTests.java
Labels: fix

#176 Hotfix/apply oauth api to interceptor exclusion
  api/src/main/java/grooteogi/config/WebConfig.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
Labels: enhancement, fix

#178 chore: Update deploy.sh to set active profile
  .travis.yml
  scripts/deploy.sh
Labels: enhancement

#181 프로덕션 서버를 위한 환경설정 파일 누락 해결
  api/build.gradle
  api/src/main/resources/application-prod.yml
Labels: enhancement, fix

#182 release v0.6.1
  api/build.gradle
  api/src/main/resources/application-prod.yml
Labels: enhancement
