Repository grooteogi/backend, pull requests merged in 2022-04, with the labels that each got.

#18 docs: Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#21 Change error handling to exception
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/dto/response/BasicResponse.java
  api/src/main/java/grooteogi/dto/response/ExceptionResponse.java
  api/src/main/java/grooteogi/exception/ApiException.java
  api/src/main/java/grooteogi/exception/ApiExceptionAdvice.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/main/java/grooteogi/service/UserService.java
Labels: enhancement

#22 setting checkstyle
  api/build.gradle
  api/config/google_checks.xml
  api/config/intellij-java-google-style.xml
  api/src/main/java/grooteogi/config/WebSecurityConfig.java
  api/src/main/java/grooteogi/controller/HashtagController.java
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/domain/Hashtag.java
  api/src/main/java/grooteogi/domain/User.java
  api/src/main/java/grooteogi/domain/UserHashtag.java
  api/src/main/java/grooteogi/domain/UserInfo.java
  api/src/main/java/grooteogi/dto/EmailCodeRequest.java
  api/src/main/java/grooteogi/dto/EmailRequest.java
  api/src/main/java/grooteogi/dto/LoginDto.java
  api/src/main/java/grooteogi/dto/Token.java
  api/src/main/java/grooteogi/dto/UserDto.java
  api/src/main/java/grooteogi/dto/response/BasicResponse.java
  api/src/main/java/grooteogi/dto/response/ExceptionResponse.java
  api/src/main/java/grooteogi/enums/HashtagType.java
  api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
  api/src/main/java/grooteogi/enums/LoginType.java
  api/src/main/java/grooteogi/exception/ApiException.java
  api/src/main/java/grooteogi/exception/ApiExceptionAdvice.java
  api/src/main/java/grooteogi/repository/UserRepository.java
  api/src/main/java/grooteogi/service/EmailService.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/main/java/grooteogi/utils/JwtProvider.java
  api/src/main/java/grooteogi/utils/RedisClient.java
Labels: enhancement

#23 refactor: Unify controller return type
  api/src/main/java/grooteogi/controller/HashtagController.java
  api/src/main/java/grooteogi/controller/UserHashtagController.java
  api/src/main/java/grooteogi/repository/HashtagRepository.java
  api/src/test/java/grooteogi/ApplicationTests.java
Labels: fix

#24 Add checkstyle suppresions to ignore javadoc error
  api/build.gradle
  api/config/checkstyle/checkstyle.xml
  api/config/checkstyle/suppressions.xml
  api/config/checkstyle/suppressions_1_2.dtd
Labels: enhancement

#25 Grtg 114 refresh token
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/main/java/grooteogi/utils/JwtProvider.java
Labels: enhancement

#26 cleanup code style
  api/src/main/java/grooteogi/controller/HashtagController.java
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/controller/UserHashtagController.java
  api/src/main/java/grooteogi/domain/Hashtag.java
  api/src/main/java/grooteogi/domain/User.java
  api/src/main/java/grooteogi/domain/UserHashtag.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/repository/HashtagRepository.java
  api/src/main/java/grooteogi/repository/UserHashtagRepository.java
  api/src/main/java/grooteogi/service/UserHashtagService.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/main/java/grooteogi/utils/JwtProvider.java
Labels: fix

#28 fix: Fix Post api Request param to Request Body
  api/src/main/java/grooteogi/controller/HashtagController.java
  api/src/main/java/grooteogi/controller/UserHashtagController.java
  api/src/main/java/grooteogi/dto/HashtagDto.java
  api/src/main/java/grooteogi/dto/UserHashtagDto.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/main/java/grooteogi/service/UserHashtagService.java
Labels: enhancement

#31 fix: Fix deleteUserHashtag Method
  api/src/main/java/grooteogi/service/UserHashtagService.java
Labels: bug, fix

#33 update basic_response and maintain user api
  api/src/main/java/grooteogi/controller/HashtagController.java
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/controller/UserHashtagController.java
  api/src/main/java/grooteogi/dto/response/BasicResponse.java
  api/src/main/java/grooteogi/service/UserService.java
Labels: enhancement

#32 feat: Add response message
  api/.gitignore
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/dto/response/ExceptionResponse.java
  api/src/main/java/grooteogi/repository/UserRepository.java
  api/src/main/java/grooteogi/service/EmailService.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/main/resources/application-dev.yml
Labels: enhancement

#34 Return headers including token when user login
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/service/UserService.java
Labels: fix

#36 feat: Create db tables related post
  api/src/main/java/grooteogi/domain/Post.java
  api/src/main/java/grooteogi/domain/PostHashtag.java
Labels: enhancement

#35 fix: Add column count in hashtag and setting count
  api/src/main/java/grooteogi/domain/Hashtag.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/repository/HashtagRepository.java
  api/src/main/java/grooteogi/repository/UserHashtagRepository.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/main/java/grooteogi/service/UserHashtagService.java
Labels: enhancement

#39 chore: Update docker-compose.local.yml to add email env
  docker-compose.local.yml
Labels: enhancement

#43 Create amazon s3 client
  api/build.gradle
  api/src/main/java/grooteogi/config/AwsS3Config.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/utils/AmazonS3Client.java
  api/src/main/resources/application-dev.yml
Labels: enhancement

#44 Set AWS S3 Environment
  api/src/main/java/grooteogi/config/AwsS3Config.java
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/utils/AwsS3Client.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application.yml
Labels: enhancement

#45 Add search post and sort by created date
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/domain/Hashtag.java
  api/src/main/java/grooteogi/domain/PostHashtag.java
  api/src/main/java/grooteogi/domain/UserHashtag.java
  api/src/main/java/grooteogi/domain/UserInfo.java
  api/src/main/java/grooteogi/repository/PostRepository.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/utils/CursorResult.java
Labels: enhancement

#46 Get KAKAO User Info using token
  api/build.gradle
  api/src/main/java/grooteogi/config/AccessDeniedHandlerConfig.java
  api/src/main/java/grooteogi/config/AuthenticationEntryPointConfig.java
  api/src/main/java/grooteogi/config/WebSecurityConfig.java
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/domain/User.java
  api/src/main/java/grooteogi/dto/OauthDto.java
  api/src/main/java/grooteogi/dto/UserDto.java
  api/src/main/java/grooteogi/enums/LoginType.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/main/java/grooteogi/utils/OauthClient.java
  api/src/main/resources/application.yml
Labels: enhancement

#49 Deal with errors when login using kakao
  api/src/main/java/grooteogi/utils/JwtProvider.java
  api/src/main/java/grooteogi/utils/OauthClient.java
Labels: bug

#50 Setting test environment with restdocs
  api/build.gradle
  api/src/docs/asciidoc/api.adoc
  api/src/main/resources/static/docs/api.html
  api/src/test/java/grooteogi/ApiDocumentUtils.java
  api/src/test/java/grooteogi/ApplicationTests.java
  api/src/test/java/grooteogi/UserDocumentationTests.java
Labels: documentation

#54 Grtg 200 edit user profile
  api/src/main/java/grooteogi/controller/ProfileController.java
  api/src/main/java/grooteogi/domain/UserInfo.java
  api/src/main/java/grooteogi/dto/ProfileDto.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/repository/UserRepository.java
  api/src/main/java/grooteogi/service/ProfileService.java
  api/src/main/java/grooteogi/utils/Validator.java
Labels: enhancement

#57 modify configurations for production
  api/src/main/java/grooteogi/config/WebConfig.java
  api/src/main/java/grooteogi/config/WebSecurityConfig.java
  api/src/main/resources/application-dev.yml
  api/src/main/resources/application-local.yml
  api/src/main/resources/application.yml
Labels: enhancement

#59 Create google oauth back logic
  api/src/main/java/grooteogi/config/WebSecurityConfig.java
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/utils/OauthClient.java
  api/src/main/resources/application.yml
Labels: enhancement

#61 Implement google oauth
  api/src/main/java/grooteogi/controller/UserController.java
  api/src/main/java/grooteogi/utils/OauthClient.java
  api/src/main/resources/application.yml
Labels: enhancement

#55 create modify user hashtag api
  api/src/main/java/grooteogi/controller/UserHashtagController.java
  api/src/main/java/grooteogi/domain/UserHashtag.java
  api/src/main/java/grooteogi/dto/UserHashtagDto.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/service/HashtagService.java
  api/src/main/java/grooteogi/service/UserHashtagService.java
Labels: enhancement

#62 Setting outlook mail server
  api/src/main/java/grooteogi/service/EmailService.java
  api/src/main/resources/application.yml
Labels: enhancement

#65 Fix: signature does not match in aws s3 config
  api/src/main/java/grooteogi/config/AwsS3Config.java
  api/src/main/resources/application.yml
Labels: bug
