Repository grooteogi/backend, pull requests merged in 2022-06, with the labels that each got.

#183 포스트 Detail response 로직 수정
  api/src/main/java/grooteogi/service/PostService.java
Labels: bug, fix

#185 feat: add isAuthor in postDto and set about that in postService
  api/src/main/java/grooteogi/dto/PostDto.java
  api/src/main/java/grooteogi/service/PostService.java
Labels: enhancement

#186 유저 닉네임 변경 로직 오류 해결
  api/src/main/java/grooteogi/mapper/UserMapper.java
  api/src/main/java/grooteogi/service/AuthService.java
  api/src/main/java/grooteogi/service/UserService.java
Labels: fix

#187 지역 Enum to String 변경 함수 생성 및 적용
  api/src/main/java/grooteogi/enums/RegionType.java
Labels: enhancement, fix

#190 release v0.6.2
  api/Dockerfile
  api/build.gradle
  api/src/main/java/grooteogi/dto/PostDto.java
  api/src/main/java/grooteogi/dto/UserDto.java
  api/src/main/java/grooteogi/enums/RegionType.java
  api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
  api/src/main/java/grooteogi/mapper/UserMapper.java
  api/src/main/java/grooteogi/service/AuthService.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/main/java/grooteogi/service/UserService.java
  api/src/main/java/grooteogi/utils/OauthClient.java
  api/src/main/resources/application.yml
  api/src/test/java/grooteogi/UserDocumentationTests.java
Labels: enhancement

#191 OAuth 문제 해결 및 jwt 빈 문자열 처리
  api/src/main/java/grooteogi/config/UserInterceptor.java
  api/src/main/java/grooteogi/controller/AuthController.java
  api/src/main/java/grooteogi/service/AuthService.java
  api/src/main/java/grooteogi/utils/JwtProvider.java
  api/src/main/java/grooteogi/utils/OauthClient.java
  api/src/main/resources/application.yml
Labels: fix

#192 해시태그 미포함 Response 로직 수정
  api/src/main/java/grooteogi/dto/PostDto.java
  api/src/main/java/grooteogi/service/PostService.java
  api/src/test/java/grooteogi/PostDocumentationTests.java
Labels: fix

#198 포스트 수정 오류 해결 및 스케쥴 조회 로직 수정
  api/src/main/java/grooteogi/mapper/PostMapper.java
  api/src/main/java/grooteogi/service/PostService.java
Labels: bug, fix

#203 Grtg 399 포스트 지역 필터링 수정
  api/src/main/java/grooteogi/controller/PostController.java
  api/src/main/java/grooteogi/service/PostService.java
Labels: fix

#202 OAuth redirect URL 변경
  api/src/main/java/grooteogi/controller/AuthController.java
Labels: fix
